org.gradle.caching=true
org.gradle.configuration-cache=true


GROUP=io.github.allopensource
VERSION_NAME=0.1.0

POM_NAME=Envy
POM_DESCRIPTION=Type-safe environment variable mapping for Kotlin
POM_URL=https://github.com/allopensource/envy

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT

POM_DEVELOPER_ID=allopensource
POM_DEVELOPER_NAME=AllOpenSource

POM_SCM_URL=https://github.com/allopensource/envy
POM_SCM_CONNECTION=scm:git:git://github.com/allopensource/envy.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com:allopensource/envy.git